title:              Oblivious Labs
email:              obliviouslabs@gmail.com
description:        We provide open source implementations of Oblivious RAM and oblivious algorithms.
author:             Oblivious Labs
baseurl:            ""
url:                "https://www.obliviouslabs.com"

# Social Profiles
twitter_username:   obliviouslabs
github_username:    obliviouslabs
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
